version: 2.1
on: 
  push: 
  branches: main
  tag: $GITHUB_SHA
jobs:
  build:
    docker:
      - image: python 
    steps:
      - run:
          name: Hello World
          command: |
            echo 'Hello World!'
