version: 2.1
#on: 
 # push: 
 # branches: main
executors:
  docker-publisher:
    environment:
      IMAGE_NAME: blya
    docker:
      - image: circleci/python 
#  tag: $CIRCLE_SHA1
jobs:
  build:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: |
            docker build -t $IMAGE_NAME:$CIRCLE_SHA1 .
