version: 2.1
on: 
  push: 
  branches: main
#  tag: $CIRCLE_SHA1
jobs:
  build:
    docker:
      - image: python
      - name ahahaha:$CIRCLE_SHA1
    steps:
      - run:
          name: Hello World
          command: |
            echo 'Hello World!'
            
