version: 2.1
on: 
  push: 
  branches: main
  environment:
      IMAGE_NAME: Blya:$CIRCLE_SHA1
#  tag: $CIRCLE_SHA1
jobs:
  build:
    docker:
      - image: python 
    steps:
      - run:
          name: Hello World
          command: |
            echo 'Hello World!'
            echo "$IMAGE_NAME"
